name: Flutter Build APK/AppBundle - CI/CD Pipeline
on:
  push:
    tags:
      - "b*.*.*"

jobs:
  build_and_push_bundle_and_apk:
    # Runs On Ubuntu
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/b')
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          channel: "stable"

      - name: Extract version and build number from tag
        run: |
          TAG_REF=${GITHUB_REF##*/}
          VERSION=${TAG_REF#b}  # Remove 'b' prefix
          VERSION=${VERSION%+*} # Extract version
          BUILD=${TAG_REF##*+}  # Extract build number
          echo "Original TAG_REF: $TAG_REF"
          echo "Extracted VERSION: $VERSION"
          echo "Extracted BUILD: $BUILD"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      # - name: Set up Keystore
      #   run: |
      #     echo "${{ secrets.KEYSTORE }}" | base64 -d > android/app/keystore.jks
      #     echo "${{ secrets.KEYPROPERTIES }}" > android/key.properties

      - name: Build Apk and AppBundle
        run: |
          flutter build appbundle --build-number=$BUILD --build-name=$VERSION --release
          flutter build apk --build-number=$BUILD --build-name=$VERSION --release
          dirname="build/app/intermediates/merged_native_libs/release/out/lib"
          folder1="$dirname/arm64-v8a"
          folder2="$dirname/armeabi-v7a"
          folder3="$dirname/x86_64"
          if [ -d "$dirname" ]; then
          zip -r symbols.zip $dirname
          if [ -d $folder1 ] && [ -d $folder2 ] && [ -d $folder3 ]; then
          zip -r sym.zip $folder1 $folder2 $folder3
          echo "3 folders also exists."
          else
          zip -r sym.zip pubspec.yaml
          echo "3 folders does not exists."
          fi
          echo "$dirname exists and is a directory."
          else
          zip -r symbols.zip pubspec.yaml
          echo "$dirname does not exist."
          fi

      - name: Upload APK & App Bundle to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/app-release.apk
            symbols.zip
            sym.zip
          retention-days: 2