name: Flutter Deploy CI/CD
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  # Build App Bundle and Upload on Play Store.
  deploy:
    runs-on: ubuntu-latest # macos-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Cache Flutter SDK and Dependencies
        id: get-cache
        uses: actions/cache@v3
        with:
          path: |
            build/
            android/.gradle/
            /.pub-cache
            /opt/hostedtoolcache/flutter/
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-deploy-caches

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          channel: "stable"

      - name: Extract version and build number from tag
        run: |
          TAG_REF=${GITHUB_REF##*/}
          VERSION=${TAG_REF#v}  # Remove 'v' prefix
          VERSION=${VERSION%+*} # Extract version
          BUILD=${TAG_REF##*+}  # Extract build number
          echo "Original TAG_REF: $TAG_REF"
          echo "Extracted VERSION: $VERSION"
          echo "Extracted BUILD: $BUILD"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      # - name: Set up Keystore
      #   run: |
      #     echo "${{ secrets.KEYSTORE }}" | base64 -d > android/app/keystore.jks
      #     echo "${{ secrets.KEYPROPERTIES }}" > android/key.properties

      - name: Build AppBundle
        run: |
          flutter build appbundle --build-number=$BUILD --build-name=$VERSION

      - name: Cache Flutter SDK and Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            build/
            android/.gradle/
            /.pub-cache
            /opt/hostedtoolcache/flutter/
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-deploy-caches

      # Decode the Base64-encoded Service Account JSON
      # - name: Decode Service Account JSON
      #   env:
      #     SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #   run: |
      #     echo "$SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > android/credentials-json.json

      # # Deploy to Play Store
      # - name: Deploy to Play Store
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     #          serviceAccountJsonPlainText: android/credentials-json.json
      #     serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_NEW }}
      #     packageName: com.saba.expense_tracker
      #     releaseFiles: build/app/outputs/bundle/release/app-release.aab
      #     track: internal # beta, alpha, internal, production