name: Flutter Checks CI/CD Pipeline
on:
  push:
    tags:
      - "checks-*"
    branches: [ "master" ]
  pull_request:
  pull_request_review:
  issue_comment:

jobs:
  # Flutter Format, Analyze and Test
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest # ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Cache Flutter SDK and Dependencies
        id: get-cache
        uses: actions/cache@v3
        with:
          path: |
            build/
            android/.gradle/
            /.pub-cache
            /opt/hostedtoolcache/flutter/
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-checks-caches

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          channel: "stable"

      - name: Format, Analyze and Test
        run: dart format --set-exit-if-changed . & flutter analyze & flutter test --no-pub & wait